services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: brokerx_conteiner
    ports:
      - 15672:15672 
      - 5672:5672
      - 61613:61613
      - 61614:61614
    command: >
       sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp &&
              rabbitmq-server"
    networks:
      - brokerx-network


networks:
  brokerx-network:
    driver: bridge